### ISSUE TITLE
JOSS paper checklist

### ISSUE THREAD

**Issue by fnattino** [phenology/cgc#62]
- [x] Rename “Abstract” -> “Summary”
- [x] Mention of other packages and how they differ:
	* scikit-learn: [2.4. Biclustering — scikit-learn 1.0.1 documentation](https://scikit-learn.org/stable/modules/biclustering.html)
	* coclust: [Coclust: a Python package for co-clustering — Coclust 0.2.1 documentation](https://coclust.readthedocs.io/en/v0.2.1/)
	* others?
- [x] “Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it.”
- [x]  Verify that paper compiles at https://whedon.theoj.org
